# Generated by Django 5.1.7 on 2025-03-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='liked',
        ),
    ]
